### ISSUE TITLE
Failed to install scale

### ISSUE THREAD

**Issue by fareedfauzi** [countercept/snake-scales#7]
Hey, can you help me about this? Scale failed to be install.

# Using snake install
```
ubuntu@ubuntu:~/snake$ snake install binwalk
Installing: binwalk
Collecting git+https://github.com/countercept/snake-scales#subdirectory=binwalk
  Cloning https://github.com/countercept/snake-scales to /tmp/pip-3wbxsdf_-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-3wbxsdf_-build/binwalk/setup.py", line 3, in <module>
        import binwalk as scale
      File "/tmp/pip-3wbxsdf_-build/binwalk/binwalk/__init__.py", line 1, in <module>
        from snake.scale import FileType, scale
    ModuleNotFoundError: No module named 'snake.scale'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-3wbxsdf_-build/binwalk
Failed to install: binwalk
```

# Using pip based
```
ubuntu@ubuntu:~/snake$ pip install git+https://github.com/countercept/snake-scales/binwalk
Collecting git+https://github.com/countercept/snake-scales/binwalk
  Cloning https://github.com/countercept/snake-scales/binwalk to /tmp/pip-n9LvPR-build
remote: Not Found
fatal: repository 'https://github.com/countercept/snake-scales/binwalk/' not found
Command "git clone -q https://github.com/countercept/snake-scales/binwalk /tmp/pip-n9LvPR-build" failed with error code 128 in None
```

**Comment by AlexKornitzer** [comment]
Right so my guess for the first one based on the error is that you have not sourced the vritual env before running the command (but this depends how you installed snake). I assume you did a bare metal install?

And for the second one it looks like the command is out of date, so I will get that updated, it needs to be something like:
`pip3 install 'git+https://github.com/countercept/snake-scales#egg=binwalk&subdirectory=binwalk'`

**Comment by fareedfauzi** [comment]
Okay I did run the virtual env

```
ubuntu@ubuntu:~/snake$ python3 -m venv env
ubuntu@ubuntu:~/snake$ source env/bin/activate
(env) ubuntu@ubuntu:~/snake$ snake install binwalk
Installing: binwalk
Collecting git+https://github.com/countercept/snake-scales#subdirectory=binwalk
  Cloning https://github.com/countercept/snake-scales to /tmp/pip-52p0gwc3-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-52p0gwc3-build/binwalk/setup.py", line 3, in <module>
        import binwalk as scale
      File "/tmp/pip-52p0gwc3-build/binwalk/binwalk/__init__.py", line 1, in <module>
        from snake.scale import FileType, scale
    ModuleNotFoundError: No module named 'snake'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-52p0gwc3-build/binwalk
Failed to install: binwalk
```

**Comment by AlexKornitzer** [comment]
Right okay so lets get this sorted :)

What you have done in the above will not work as that is a clean venv that snake has not been installed into. Ah and apologies if you ran `sys/install.sh` then snake is not installed into a venv but into the default Python 3, so looks like we have a different problem to deal with.

So I think I might need more information to help you, what version of Ubuntu are you on? Did you use `sys/install.sh`? Did the script error? Does snake run successfully for you?

Based on your original error it seems like snake did not successfully install as it is failing to import `snake.scale`. Does the following error for you?
```
python3 -c 'import snake.scale'
```

**Comment by fareedfauzi** [comment]
Thanks Alex for the reply.

When I change to Ubuntu 17, the installation script was run smoothly and successful. Non of error occurred.
